import { describe, expect, test } from "bun:test";
import { formatProviderOrdinal, isLegacyProviderDisplayName } from "./ai-provider-options.ts";

describe("AI provider display names", () => {
  test("formats sequential Chinese provider names", () => {
    expect([1, 2, 10, 11, 20, 21].map((position) => formatProviderOrdinal(position, "zh-CN")))
      .toEqual(["一", "二", "十", "十一", "二十", "二十一"]);
    expect(formatProviderOrdinal(2, "en-US")).toBe("2");
  });

  test("recognizes names generated by the legacy protocol defaults", () => {
    expect(isLegacyProviderDisplayName("OpenAI-compatible", "openai-compatible")).toBe(true);
    expect(isLegacyProviderDisplayName("OpenRouter", "openai-compatible")).toBe(false);
  });
});
